import type { Metadata } from 'next';

import './globals.scss';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function LandingLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<link
					href="https://fonts.cdnfonts.com/css/sf-pro-display?styles=98774,98772,98773,98775,98770"
					rel="stylesheet"
				></link>
			</head>
			<body style={{ scrollBehavior: 'smooth' }}>{children}</body>
		</html>
	);
}
