name: Publish Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          context: ./tiddle/
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/tiddleme/tiddleFrontend/tiddleFrontend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'develop'

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo docker pull docker.pkg.github.com/tiddleme/tiddleFrontend/tiddleFrontend:latest
            sudo docker-compose stop
            sudo docker-compose rm tiddle
            touch .env
            echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env
            echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env
            echo NEXT_PUBLIC_DJANGO_HOST=${{ secrets.NEXT_PUBLIC_DJANGO_HOST }} >> .env
            sudo docker-compose up -d
